# Generated by Django 3.1.1 on 2020-09-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200919_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='fund_account_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='name',
            field=models.CharField(default='Sanket', max_length=500),
            preserve_default=False,
        ),
    ]
