org: mario2334
app: gigvid
service: gigvid-api

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: ap-south-1
  timeout: 30

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /test_this_api
          method: GET
          cors: true

      - http:
          path: /create_user
          method: POST
          cors: true

      - http:
          path: /login
          method: POST
          cors: true
