service: gigvid-api

provider:
  name: aws
  runtime: nodejs12.18
  stage: dev
  region: ap-south-1

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
