# Generated by Django 3.1.1 on 2020-09-17 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='header_image',
            field=models.URLField(default='https://bit.ly/2FDitkQ'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
