# Generated by Django 3.1.1 on 2020-09-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_gig_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gig',
            old_name='url',
            new_name='host_url',
        ),
        migrations.AddField(
            model_name='gig',
            name='join_url',
            field=models.URLField(default='https://www.testvid.com'),
        ),
    ]
