# Generated by Django 3.1.1 on 2020-09-18 22:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200919_0401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gig',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='gig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
