# Generated by Django 3.1.1 on 2020-09-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200919_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='price',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
