# Generated by Django 3.1.1 on 2020-09-20 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_gig_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_link_id', models.URLField()),
                ('final_price', models.IntegerField()),
                ('is_successful', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='gig',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
