# Generated by Django 3.1.1 on 2020-09-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200920_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_link_id',
            field=models.CharField(max_length=500),
        ),
    ]
